placement_group:
  name: ecp-thais
  strategy: cluster # {cluster, spread}
security_group:
  name: ecp-thais
efs:
  name: efs-thais-ecp
  tag: efs-tag-thais
pub_key: ~/.clap/private/ec2_access_key.pub
pem_key: ~/.clap/private/ec2_access_key.pem
