benchmark: ecp
vm_type: r5.xlarge
nodes: 32
num_exec: 10
apps:
  - AMG
  - Ember
  - ExaMiniMD
  - Laghos
  - MACSio
  - miniAMR
  - miniQMC
  - miniVite
  - NEKbone
  - PICSARlite
  - SW4lite
  - SWFFT
  - Thornado-mini
  - XSBench
efs_ip: 172.31.7.21
dir: "/home/thais/Dev/master/clapp-experiments"
# dir é o caminho até a pasta ES-Benchmark/experiments
#    -> resultados irão ser salvos dentro de ES-Benchmark/experiments/experimental_results
